server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shw2${datasource_url_end_str}
    username: root
    password: root
  redis:
    host: locahost
    port: 6379
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
logging:
  level: error
  level.top: warn
cas:
  debug: false
  login-success-url: http://localhost:8090
  local-server-url: http://localhost:8080