# 开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shw2${datasource_url_end_str}
    username: root
    password: root
  jpa:
    show-sql: true
logging:
  level: debug
  level.top: debug