spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
cas:
  server-url: http://login.greathiit.com
  login-url: http://login.greathiit.com/login
  logout-url: http://login.greathiit.com/logout
datasource_url_end_str: ?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false