# 线上环境
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shw2${datasource_url_end_str}
    username: root
    password: root
logging:
  level: error
  level.top: warn
  #file: