server:
  port: 8761
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
spring:
  application:
    name: es